docs_dir: doc/book
site_dir: doc/html
nav:
    - index.md
    - Intro: intro.md
    - Usage: usage-examples.md
site_name: laminas-psr7bridge
site_description: laminas-psr7bridge
repo_url: 'https://github.com/laminas/laminas-psr7bridge'
